CREATE TABLE USUARIO(
    ID TEXT PRIMARY KEY ,
    LOGIN VARCHAR(200) DEFAULT 'convidado',
    EMAIL TEXT NOT NULL UNIQUE,
    PASSWORD TEXT NOT NULL

);

CREATE TABLE LIVRO (
    ID TEXT PRIMARY KEY ,
    NOME VARCHAR(200) NOT NULL,
    PRECO DECIMAL,
    ISBN TEXT NOT NULL UNIQUE,
    DT_CRIACAO DATE
);

CREATE TABLE ESTOQUE(
    ID TEXT PRIMARY KEY ,
    ID_LIVRO TEXT REFERENCES LIVRO,
    QUANTIDADE INTEGER
);

CREATE TABLE COMPRA(
    ID TEXT PRIMARY KEY ,
    ID_LIVRO TEXT REFERENCES LIVRO,
    ID_USUARIO TEXT REFERENCES USUARIO,
    DT_TRANSACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    VALOR DECIMAL CHECK ( VALOR>0 )
);